### ISSUE TITLE
It doesn't work on prestashop 8.1

### ISSUE THREAD

**Issue by ArminTanzanian** [blastanders/Prestashop-Resend-Order-Confirmation-Email#3] opened 2023-08-20 12:28 UTC
Hello, I have installed your module in a Prestashop 8.1 and it does not work. I get this error: Failed to start the session because headers have already been sent by..
Is there any chance to update it?
Thank you

**Comment by blastanders** [comment] 2023-08-20 13:17
Hi mate, its late where i am. Ill have a look at this tomorrow morning in about 12 hours. cheers
________________________________
From: ArminTanzanian ***@***.***>
Sent: Sunday, August 20, 2023 12:28 PM
To: blastanders/Prestashop-Resend-Order-Confirmation-Email ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [blastanders/Prestashop-Resend-Order-Confirmation-Email] It doesn't work on prestashop 8.1 (Issue #3)


Hello, I have installed your module in a Prestashop 8.1 and it does not work. I get this error: Failed to start the session because headers have already been sent by..
Is there any chance to update it'
Thank you

**Comment by ArminTanzanian** [comment] 2023-08-20 13:22
Thanks for your quick response.

**Comment by blastanders** [comment] 2023-08-21 01:01
> Thanks for your quick response.

Hi mate, I just installed the plugin to a prestashop 8.1 shop and got no errors. So I suspect the issue is specific to your site. Happy to have a look at your website if you want. 

You can create a login for me and send me the admin URL, login and password to aaron.zheng404@gmail.com I should have time to jump onto it today. 

You can delete my login after the issue is resolved.

**Comment by blastanders** [comment] 2023-08-21 13:51
Closing this now since i have fixed it on your site, and the code on git.

Thanks again for pointing it out.

**Closed as completed by blastanders** 2023-08-21 13:51 UTC
